#!/usr/bin/env python3
"""Generate BibTeX only from terminally verified citation-lock metadata."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "citation_lock.json"
OUT = ROOT / "references.bib"


def escape(value: object) -> str:
    text = str(value)
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("_", r"\_")
        .replace("#", r"\#")
    )


def entry(record: dict[str, object]) -> str:
    if record["status"] != "verified":
        raise RuntimeError(f"citation lock is not terminal: {record['key']}")
    metadata = record["metadata"]
    key = record["key"]
    identifier = record["identifier"]
    authors = " and ".join(escape(author) for author in metadata["authors"])
    title = escape(metadata["title"])
    year = metadata["year"]
    if identifier.startswith("arxiv:"):
        arxiv_id = identifier.split(":", 1)[1]
        return f"""@article{{{key},
  author = {{{authors}}},
  title = {{{{{title}}}}},
  journal = {{arXiv preprint arXiv:{arxiv_id}}},
  year = {{{year}}},
  url = {{https://arxiv.org/abs/{arxiv_id}}}
}}"""
    doi = identifier.split(":", 1)[1]
    return f"""@misc{{{key},
  author = {{{authors}}},
  title = {{{{{title}}}}},
  year = {{{year}}},
  doi = {{{doi}}},
  url = {{https://doi.org/{doi}}}
}}"""


def main() -> None:
    lock = json.loads(LOCK.read_text(encoding="utf-8"))
    records = lock.get("records")
    if not isinstance(records, list) or not records:
        raise RuntimeError("citation lock contains no records")
    output = [
        "% GENERATED FILE. DO NOT EDIT BY HAND.",
        "% Source: citation_lock.json, generated by scripts/generate_bibliography.py.",
        "",
    ]
    output.extend(entry(record) + "\n" for record in records)
    OUT.write_text("\n".join(output), encoding="utf-8")


if __name__ == "__main__":
    main()
